### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by bblumberg** [UniversalRobots/Universal_Robots_ROS2_Driver#114]
As of today, scaled_joint_trajectory_controller doesn't build. I tracked it down to changes made to  joint_trajectory_controller in
https://github.com/ros-controls/ros2_controllers.git

halt() disappeared and a few instance variables have been renamed.

**Comment by gavanderhoorn** [comment]
It would be good to pin versions of dependencies in [Universal_Robots_ROS2_Driver.repos](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/9106b97ea61942f48472e6395489b5d10182422c/Universal_Robots_ROS2_Driver.repos) to prevent this from happening in the future.

**Comment by gexter192** [comment]
Hotfix: 

In `Universal_Robots_ROS2_Driver.repos` change version of  `ros2_controllers` to last working version:


```
  ros2_controllers:
    type: git
    url: https://github.com/ros-controls/ros2_controllers.git
    version: master
```


```
  ros2_controllers:
    type: git
    url: https://github.com/ros-controls/ros2_controllers.git
    version: 0.2.1
```

Should I make a pull request?
