### ISSUE TITLE
clipped/overshoot in velocity profiles when sending trajectories with Scaled_joint_trajectory_controller 

### ISSUE THREAD

**Issue by Yazan-Soliman** [UniversalRobots/Universal_Robots_ROS2_Driver#1180]
### Affected ROS2 Driver version(s)

ros-humble-ur/jammy,now 2.2.16-5jammy.20241029.212959 amd64

### Used ROS distribution.

Humble

### Which combination of platform is the ROS driver running on.

Ubuntu Linux with standard kernel

### How is the UR ROS2 Driver installed.

From binary packets

### Which robot platform is the driver connected to.

UR E-series robot

### Robot SW / URSim version(s)

5.16.0

### How is the ROS driver used.

Through the robot teach pendant using External Control URCap

### Issue details

# Summary
UR10e experiences clipping motion when controlled with scaled_joint_trajectory_controller.

## Issue details

I am conducting research for my master's thesis with a UR10e robot, where I need to send trajectories over the scaled_JTC. 
on the Teach Pendant the safety limits are set to least restrictive settings.
Trajectories are computed with Ruckig trajectory planner from point A to point B and within the robot hardware limitations i.e velocities and accelerations.

our initial thoughts that the tracking error is experiencing some lag so we plotted the error from the controller state as below.
![error](https://github.com/user-attachments/assets/de422664-20ac-44b2-839b-309d3c006c92)

controller Feedback
![feedback](https://github.com/user-attachments/assets/158730f4-1f41-4c4f-a6ab-c334e82ca9a3)

as seen the controller state error does not indicate any unexpected deviations. To address the issue, we reduced acceleration limits to 8. rad/s² for all joints  which should be within the capabilities of a robot like UR10e. However the behavior remained unchanged.

another example is shown below.

![5_ruckig_qd_noise](https://github.com/user-attachments/assets/abce212b-66da-4a68-87a6-82e4786f49e6)
![5_ruckig_q_noise](https://github.com/user-attachments/assets/f46ea8ff-0b0e-491c-82f0-c9453d09536a)
![5_trajectory_plot](https://github.com/user-attachments/assets/74fe5bfd-c548-40b4-89a4-946eb841de7f)

ps: what was also unclear why does controller_state/error/positions shows a velocity error as seen from the first plot ?

below are relevant controller parameters.

``` Yaml

scaled_joint_trajectory_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    allow_nonzero_velocity_at_trajectory_end: false
    constraints:
      stopped_velocity_tolerance: 0.2
      goal_time: 0.0
      shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
      shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
      elbow_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
      wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
    speed_scaling_interface_name: speed_scaling/speed_scaling_factor
```

# Workaround Suggestion
The issue could be mitigated when sending trajectories with a longer duration.

### Accept Public visibility

- [X] I agree to make this context public
