### ISSUE TITLE
Test Fail Locally

### ISSUE THREAD

**Issue by erichlf** [UniversalRobots/Universal_Robots_ROS2_Driver#1206]
### Affected ROS2 Driver version(s)

humble

### Used ROS distribution.

Humble

### Which combination of platform is the ROS driver running on.

Docker

### How is the UR ROS2 Driver installed.

Build both the ROS driver and UR Client Library from source

### Which robot platform is the driver connected to.

URSim in docker

### Robot SW / URSim version(s)

Proxmox 5.11.11

### How is the ROS driver used.

Headless without using the teach pendant

### Issue details

# Summary
I am attempting to run the ur ros2 driver tests. But the tests all fail.

## Issue details
I have tried a combination of things, but they all involve docker. I have tried just running the tests via `colcon test ...`, which then states that URSim connection couldn't be established, I have tried running URSim in its own docker container with the driver tests running in another docker container, and finally I have tried running a docker container for the driver and then issuing `ros2 run ur_robot_client start_usim.sh` in this case I get the same couldn't connect to URSim issue. The only version that successfully connected to URSim was running two containers with a network setup. The rest will be about that version.

## Steps to Reproduce
First thing is to clone the appropriate repos into ${HOME}/workspace/ur/src. Then I have the following `.env`
```
PUID=${PUID}
PGID=${PGID}
HOME=${HOME}
WORKSPACE="${HOME}/workspace/ur"
POLYSCOPE=5.11.11
URSIM_WS="${WORKSPACE}"
```
and the following docker-compose file
```yaml
services:
  ursim:
    image: universalrobots/ursim_e-series:${POLYSCOPE}
    container_name: ursim
    ports:
      - 5900:5900
      - 6080:6080
      # added
      - 29999:29999
      - 30001:30001
      - 30002:30002
      - 30004:30004
      - 50002:50002
    environment:
      ROBOT_MODEL: UR10
      TZ: Europe/Amsterdam
    volumes:
      - ${URSIM_WS}/.ursim/urcaps:/ursim/.urcaps
      - ${URSIM_WS}/.ursim/programs:/ursim/programs
      - ${URSIM_WS}/.ursim/gui:/ursim/GUI
    networks:
      ursim_net:
        ipv4_address: 192.168.56.101

  ur-driver:
    build: .
    env_file: variables.env
    user: ${PUID:-1000}:${PGID:-1000}
    container_name: ur-driver-test
    tty: true
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${HOME}/.Xauthority:/home/ros/.Xauthority:rw
      - /dev:/dev
      # issue where opencv can't display an image
      - /run/user/${PUID:-1000}/at-spi/bus_0:/run/user/${PUID:-1000}/at-spi/bus_0:ro
      - ${WORKSPACE}:/home/ros/ros_ws
    group_add:
      - video
      - tty
    privileged: true
    devices:
      - /dev/dri
    networks:
      - ursim_net
    command: bash

networks:
  ursim_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.56.0/24
```
with `Dockerfile`:
```
ARG ROS_DISTRO=humble
ARG PREFIX=

FROM osrf/ros:humble-desktop-full AS ros_user_setup
# Create a non-root user
ENV ROS_USER=ros
ARG ROS_USER_UID=1000
ARG ROS_USER_GID=$ROS_USER_UID

RUN groupadd --gid $ROS_USER_GID $ROS_USER && \
  useradd -s /bin/bash --uid $ROS_USER_UID --gid $ROS_USER_GID -m $ROS_USER \
  # [Optional] Add sudo support for the non-root user
  && apt-get update \
  && apt-get install -y --no-install-recommends sudo \
  && echo $ROS_USER ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$ROS_USER \
  && chmod 0440 /etc/sudoers.d/$ROS_USER

RUN apt-get update \
  # install build tools
  && sudo apt-get install -y --no-install-recommends \
    alsa-utils \
    apt-rdepends \
    build-essential \
    git \
    # install useful tools
    ccache \
    wget \
    curl \
    htop \
    vim \
    clang-format \
    # install ros specifics
    libpoco-dev \
    libprotobuf-dev \
    protobuf-compiler \
    python3-colcon-common-extensions \
    python3-pip \
    python3-rosdep \
    python3-vcstool \
  # apt clean-up
  && sudo apt-get autoremove -y \
  && sudo rm -rf /var/lib/apt/lists/*

USER $ROS_USER

# Set up the entrypoint
ENTRYPOINT [ "/ros_entrypoint.sh" ]
CMD ["bash"]
```
Then I run 
1. `docker compose up` everything comes up and I get a link that point to the URSim.
2. `docker exec -it ur-driver-test bash`
3. `sudo apt install docker.io` 
4. `source /opt/ros/humble/setup.bash`
5. `cd ~/ros_ws`
6. `rosdep update && rosdep -q install --from-paths src/ --ignore-src -y --rosdistro "${ROS_DISTRO}"`
7. `colcon build --symlink-install --merge-install --packages-up-to ur --cmake-args -DUR_ROBOT_DRIVER_BUILD_INTEGRATION_TESTS=on`
8. `source install/setup.bash`
9. `colcon test --merge-install --event-handlers console_cohesion+ --packages-select ur_robot_driver`

## Expected Behavior
I would have expected that the tests pass.

## Actual Behavior
All tests fail

# Workaround Suggestion
No idea

### Relevant log output

```shell
The following tests FAILED:
	  1 - test_launch_args.py (Failed)
	  2 - test_dashboard_client.py (Failed)
	  3 - test_robot_driver.py (Failed)
	  4 - test_integration_test_controller_switch.py (Failed)
	  5 - test_urscript_interface.py (Failed)
```

### Accept Public visibility

- [X] I agree to make this context public
