### ISSUE TITLE
Local planner gets stuck because of driver constraints

### ISSUE THREAD

**Issue by skaeringur97** [UniversalRobots/Universal_Robots_ROS2_Driver#535]
I'm implementing hybrid planning to the UR10e robot and the local planner gets stuck often, asking for a re-plan from the global planner causing this action:

https://user-images.githubusercontent.com/31903354/201063046-b55b7f32-2abc-4a6d-b02f-1e19ced651c7.mp4

After a lot of debugging I found that it's caused by these lines in ur_controllers.yaml:
```
shoulder_pan_joint: { trajectory: 0.2, goal: 0.1 }
shoulder_lift_joint: { trajectory: 0.2, goal: 0.1 }
elbow_joint: { trajectory: 0.2, goal: 0.1 }
wrist_1_joint: { trajectory: 0.2, goal: 0.1 }
wrist_2_joint: { trajectory: 0.2, goal: 0.1 }
wrist_3_joint: { trajectory: 0.2, goal: 0.1 }
```
If I increase this threshold or remove these lines, the problem goes away. Is it possible that these values are too low? Increasing them to 0.3 and 0.15 mostly solves this issue:

https://user-images.githubusercontent.com/31903354/201064915-2e6db542-3924-413c-b0e4-b219c1ab1fce.mp4

Removing these lines completely fixes this issue:

https://user-images.githubusercontent.com/31903354/201065216-7f3df691-10a2-4a69-8a0d-e4edde5783fa.mp4

**Comment by skaeringur97** [comment]
Making the joint limits stricter also improves the performance, even with 0.2 and 0.1 as the tolerances

**Comment by skaeringur97** [comment]
I'll close this issue since this seems to be solved by limiting joints and keeping the tolerances the same

**Comment by marioesteban11** [comment]
Hi @skaeringur97, can u post here a video with the final result pls.

Thanks in advance

**Comment by skaeringur97** [comment]
@marioesteban11 

https://user-images.githubusercontent.com/31903354/203079095-7e12c6c5-72f1-445d-9d20-1474dd5712bf.mp4

**Comment by marioesteban11** [comment]
May I know, which joint_limits and ur_controllers parameters are you using? @skaeringur97

**Comment by skaeringur97** [comment]
@marioesteban11 

Joint limits:
```
joint_limits:
  shoulder_pan_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 330.0
    max_position: !degrees  -50.0
    max_velocity: !degrees  120.0
    min_position: !degrees -200.0
  shoulder_lift_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 330.0
    max_position: !degrees  5.0
    max_velocity: !degrees  -90.0
    min_position: !degrees -200.0
  elbow_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 150.0
    # we artificially limit this joint to half its actual joint position limit
    # to avoid (MoveIt/OMPL) planning problems, as due to the physical
    # construction of the robot, it's impossible to rotate the 'elbow_joint'
    # over more than approx +- 1 pi (the shoulder lift joint gets in the way).
    #
    # This leads to planning problems as the search space will be divided into
    # two sections, with no connections from one to the other.
    #
    # Refer to https://github.com/ros-industrial/universal_robot/issues/265 for
    # more information.
    max_position: !degrees  -5.0
    max_velocity: !degrees  180.0
    min_position: !degrees -150.0
  wrist_1_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: !degrees  220.0
    max_velocity: !degrees  180.0
    min_position: !degrees -220.0
  wrist_2_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: !degrees  220.0
    max_velocity: !degrees  180.0
    min_position: !degrees -220.0
  wrist_3_joint:
    # acceleration limits are not publicly available
    has_acceleration_limits: false
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_effort: 56.0
    max_position: !degrees  220.0
    max_velocity: !degrees  180.0
    min_position: !degrees -220.0
```

Parameters I use:
```
Driver - robot_ip:=aaa.bbb.cc.d use_fake_hardware:=true initial_joint_controller:=joint_trajectory_controller
Moveit -  use_fake_hardware:=true ur_type:=ur10e use_sim_time:=true launch_servo:=false
```
Reasons explained in #503 except for launch_servo:=false, I added that because for some reason psi.getKnownObjectNames() doesn't work for objects published to a move_group node before the current node is started. If I have launch_servo:=false, it works as expected
