### ISSUE TITLE
Can not plan simple motions after applying calibration

### ISSUE THREAD

**Issue by firesurfer** [UniversalRobots/Universal_Robots_ROS2_Driver#931]
### Feature summary

Hi,

we just finished the mechanical setup of the second version of our machine. Today a read the kinematics calibration from the new arms and applied them to the URDF. 
Interestingly especially the PILZ planner (linear in the provided example) is not able the plan motions that  it were able to plan before applying the calibration. 

![image](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/assets/8481806/cb42b0c5-9ce9-4695-b1aa-fb756ca59de8)

I disabled all machine specific parts in RVIZ for the screenshot but I guess the point becomes clear. We want to perform a linear cartesian motion from `start_pose` to `end_pose`. 

PILZ reports either `unable to find IK Solution` or the typical `Joint velocity limit of ur_top/elbow_joint violated. Set the velocity scaling factor lower! Actual joint velocity is -33.3537, while the limit is 3.14159. `

With the default kinematics applied the planning succeeds. 

The kinematics read from the arm:
```
kinematics:
  shoulder:
    x: 0
    y: 0
    z: 0.18056132253822044
    roll: -0
    pitch: 0
    yaw: 2.2439482151408174e-07
  upper_arm:
    x: 0.0001730271946047779
    y: 0
    z: 0
    roll: 1.5703136403087588
    pitch: 0
    yaw: 4.741412193447898e-06
  forearm:
    x: -0.4783046168746562
    y: 0
    z: 0
    roll: 3.1415006505292848
    pitch: 3.1413102504401502
    yaw: 3.1415922567654904
  wrist_1:
    x: -0.36002174741464615
    y: -0.00048803098180374852
    z: 0.17432934076906578
    roll: 0.0027994696976741183
    pitch: -4.9009044730039759e-05
    yaw: -2.9541451840223513e-06
  wrist_2:
    x: 1.8493640688227288e-05
    y: -0.11970324846035348
    z: 0.00019042956250675861
    roll: 1.5692054810633871
    pitch: 0
    yaw: -2.794478333677762e-07
  wrist_3:
    x: 3.9335569007590755e-05
    y: 0.11558991871393763
    z: 0.00010931162624213268
    roll: 1.5717420112877298
    pitch: 3.1415926535897931
    yaw: -3.1415922617259731
  hash: ....
```
